# Paths to host tools and target binaries for run-qemu.sh.
# Relative paths are relative to directory from where run-qemu.sh is invoked.

# Scripts that source this are assumed to be invoked from hpsc-bsp/
WORKING_DIR="$(realpath -s "$PWD/..")"

KERNEL_PATH=$WORKING_DIR/linux-hpsc/arch/arm64/boot

HPSC_HOST_UTILS_DIR=${WORKING_DIR}/hpsc-utils/host
SRAM_IMAGE_UTILS=${HPSC_HOST_UTILS_DIR}/sram-image-utils
NAND_CREATOR=${HPSC_HOST_UTILS_DIR}/qemu-nand-creator

# Output files from the Yocto build
HPPS_FW=$WORKING_DIR/arm-trusted-firmware/build/hpsc/debug/bl31.bin
HPPS_BL=$WORKING_DIR/u-boot-a53/u-boot.bin
HPPS_DT=$KERNEL_PATH/dts/hpsc/hpsc.dtb
HPPS_KERN_BIN=$KERNEL_PATH/Image.gz
HPPS_KERN=uImage # generated by this script
HPPS_RAMDISK=$WORKING_DIR/hpsc-bsp/poky/build/tmp/deploy/images/zcu102-zynqmp/rootfs.cpio.gz.u-boot

# Output files from the hpsc-baremetal build
BAREMETAL_DIR=${WORKING_DIR}/hpsc-baremetal
TRCH_APP=${BAREMETAL_DIR}/trch/bld/trch.elf
RTPS_APP=${BAREMETAL_DIR}/rtps/bld/rtps.elf

# Output files from the hpsc-R52-uboot build
RTPS_BL_DIR=${WORKING_DIR}/u-boot-r52
RTPS_BL=${RTPS_BL_DIR}/u-boot.bin

# Output files from the qemu/qemu-devicetree builds
QEMU_DIR=$WORKING_DIR/qemu-bld/aarch64-softmmu
QEMU_DT_FILE=$WORKING_DIR/qemu-devicetrees/LATEST/SINGLE_ARCH/hpsc-arch.dtb

# Off-chip memory images. Created blank by run-qemu.sh if abscent.
HPPS_NAND_IMAGE=rootfs_nand.bin
HPPS_SRAM_FILE=hpps_sram.bin
TRCH_SRAM_FILE=trch_sram.bin

# System configuration interpreted by TRCH
SYSCFG=syscfg.ini
SYSCFG_SCHEMA=syscfg-schema.json
SYSCFG_BIN=syscfg.bin # generated by this script
